# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/
# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
# For more information, visit the docs: https://espanso.org/docs/

global_vars:
  - name: "github"
    type: echo
    params:
      echo: "https://github.com/Vuks69"

matches:
  # Shill espanso
  - trigger: "::espanso"
    replace: "I use [Espanso](<https://espanso.org>), it's a text expander that works on all platforms and is open source. You can see my config [here](<{{github}}/espanso-config>)."

  # Shill my server config
  - trigger: "::nixos"
    replace: "[my nixos server config](<{{github}}/nixos-config>)"

  # Print the current date
  - trigger: "::date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"
