# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/
# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  # For more information, visit the docs: https://espanso.org/docs/

  - trigger: "::espanso"
    replace: "I use [Espanso](https://espanso.org) to make my life easier. It's a text expander that works on all platforms and is open source."

  - trigger: "::nixos"
    replace: "[my nixos config](<https://github.com/Vuks69/nixos-config>)"

  # Print the current date
  - trigger: "::date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  # gets the relative discord timestamp
  # format is <t:1745788907:R>, replace middle with unix timestamp
  - trigger: "::ts"
    replace: "<t:{{unixtime}}:R>"
    vars:
      - name: "timestamp_form"
        type: form
        params:
          layout: "Please enter relative time (1s,1m,1h,1d,1w,1M,1y,just try anything tbh): [[time]]"
      - name: "unixtime"
        type: script
        params:
          args:
            - python
            - C:\Users\Konrad\scoop\persist\espanso\.espanso\scripts\discord-timestamp.py
            - "{{timestamp_form.time}}"
