# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/
# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

global_vars:
  - name: "unixtime"
    type: script
    params:
      args:
        - python
        - "%CONFIG%\\scripts\\discord-timestamp.py"
        - "{{timestamp_form.time}}"

matches:
  # For more information, visit the docs: https://espanso.org/docs/

  - trigger: "::espanso"
    replace: "I use [Espanso](<https://espanso.org>), it's a text expander that works on all platforms and is open source. You can see my config [here](<https://github.com/Vuks69/espanso-config>)."

  - trigger: "::nixos"
    replace: "[my nixos config](<https://github.com/Vuks69/nixos-config>)"

  # Print the current date
  - trigger: "::date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  # gets the discord timestamp
  # format is <t:1745788907:R>, replace middle with unix timestamp, :R with appropriate format
  # https://dateparser.readthedocs.io/en/latest/
  # https://gist.github.com/LeviSnoot/d9147767abeef2f770e9ddcd91eb85aa
  - trigger: "::ts"
    replace: "<t:{{unixtime}}:{{fmt}}>"
    vars:
      - name: "timestamp_form"
        type: form
        params:
          layout: |
            Please enter the date you want to convert to a discord timestamp.
            You can use:
            Relative time ('1 min ago', '3 months, 1 week and 1 day ago', 'in 2 days', 'tomorrow')
            A date ('12/12/12', 'August 14, 2015 EST', 'July 4, 2013 PST', '21 July 2013 10:15 pm +0500')
            [[time]]
      - name: fmt
        type: choice
        params:
          values:
            - label: "Relative Time | 3 years ago"
              id: "R"
            - label: "Default | 28 November 2018 09:01"
              id: "f"
            - label: "Short | Time 09:01"
              id: "t"
            - label: "Long | 09:01:00"
              id: "T"
            - label: "Short Date | 28/11/2018"
              id: "d"
            - label: "Long Date | 28 November 2018"
              id: "D"
            - label: "Short Date/Time | 28 November 2018 09:01"
              id: "f"
            - label: "Long Date/Time | Wednesday, 28 November 2018 09:01"
              id: "F"
